### ISSUE TITLE
Mining / reverting blocks

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-rivet#71]
Add a functionality to mine blocks, as is possible in Rivet.

It is also possible to **revert** the mined block!

Reference in devnet-rs: https://0xspaceshard.github.io/starknet-devnet-rs/docs/blocks

![image](https://github.com/user-attachments/assets/372e4336-2620-40cd-911f-9a99140a9c95)

**Comment by qperrot** [comment]
https://github.com/0xSpaceShard/starknet-rivet/pull/45
